#use_frameworks!

platform :ios, '8.0'

target 'WirelessTransFile_Example' do
  pod 'WirelessTransFile', :path => '../'
  pod 'CocoaHTTPServer', :git => 'https://github.com/leeliangliang/CocoaHTTPServer.git'
  
  target 'WirelessTransFile_Tests' do
    inherit! :search_paths

    
  end
end
