use_frameworks!

platform :ios, '8.0'

target 'WirelessTransFile_Example' do
  pod 'WirelessTransFile', :path => '../'

  target 'WirelessTransFile_Tests' do
    inherit! :search_paths

    
  end
end
